name: update-readme
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: run script
        run: python scripts/update-readme.py

      - name: commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "script updated readme" || echo "nothing to commit"
          git push
